name: Build Kumo and create publish docker images
on: 
  push:
    branches:
      - testing

jobs:
  build-and-publish-frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - name: Checkout repository
        uses: https://github.com/actions/checkout@v4
      - name: Use Node.js
        uses: https://github.com/actions/setup-node@v4
        with:
          node-version: '23.4.0'
      - name: Install Node dependencies
        run: npm install
      - name: Install angular cli
        run: npm install -g @angular/cli
      - name: Build project
        run: ng build --configuration production
      - name: Set up Docker Buildx
        uses: https://github.com/docker/setup-buildx-action@v3
        with:
          driver-opts: network=host
          config-inline: |
            [registry."docker.rares.is"]
      - name: Build and push Docker image
        uses: https://github.com/docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile-frontend
          push: true
          tags: "docker.rares.is/kumo-frontend:${{gitea.sha}},docker.rares.is/kumo-frontend:latest"
  build-and-publish-backend:
    runs-on: ubuntu-maven 
    defaults:
      run:
        working-directory: ./backend
    steps:
      - name: Checkout repository
        uses: https://github.com/actions/checkout@v4
      - name: Setup Java
        uses: https://github.com/actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '17'
      - name: Build project
        run: mvn package -Pdeploy -T8
      - name: Set up Docker Buildx
        uses: https://github.com/docker/setup-buildx-action@v3
        with:
          driver-opts: network=host
          config-inline: |
            [registry."docker.rares.is"]
      - name: Build and push Docker image
        uses: https://github.com/docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile-backend
          push: true
          tags: "docker.rares.is/kumo-backend:${{gitea.sha}},docker.rares.is/kumo-backend:latest"