spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/kumo
    username: postgres
    password: postgres
  jpa:
    hibernate.ddl-auto: create-drop
    database-platform: org.hibernate.dialect.PostgreSQLDialect

redis:
  host: localhost